name: Trigger Jenkins Job

on:
  push:
    branches:
      - master
      - staging
      - live

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Get Branch Name
        id: vars
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Trigger Jenkins Job
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          BASE_URL: https://d143-2607-fb90-c13e-502-b119-7f8f-8555-daa.ngrok-free.app  # Replace with your Jenkins URL
        run: |
          branch=${{ steps.vars.outputs.branch }}

          if [[ "$branch" == "master" ]]; then
            JOB_URL="$BASE_URL/job/file-writer-multi-branch/build"
          elif [[ "$branch" == "staging" ]]; then
            JOB_URL="$BASE_URL/job/file-writer-multi-branch/buildWithParameters?BRANCH=$branch"
          elif [[ "$branch" == "live" ]]; then
            JOB_URL="$BASE_URL/job/file-writer-multi-branch/buildWithParameters?BRANCH=$branch"
          fi

          echo "Triggering Jenkins job for $branch: $JOB_URL"

          curl -X POST "$JOB_URL" \
            --user "$JENKINS_USER:$JENKINS_TOKEN"
