name: Trigger Jenkins on Push

on:
  push:
    branches: [ master, live, staging ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        id: vars
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Trigger Jenkins Based on Branch
        env:
          GITHUB_REPO: ${{ github.repository }}
          COMMIT_ID: ${{ github.sha }}
        run: |
          branch=${{ steps.vars.outputs.branch }}
          
          if [[ "$branch" == "master" ]]; then
            curl -X POST https://d143-2607-fb90-c13e-502-b119-7f8f-8555-daa.ngrok-free.app/github-webhook/ \
              -H "Content-Type: application/json" \
              -H "X-GitHub-Event: push" \
              -d '{
                    "ref": "refs/heads/master",
                    "repository": {
                      "full_name": "'"${GITHUB_REPO}"'",
                      "clone_url": "https://github.com/'"${GITHUB_REPO}"'.git"
                    },
                    "head_commit": {
                      "id": "'"${COMMIT_ID}"'",
                      "message": "Triggered via GitHub Actions"
                    }
                  }'

          elif [[ "$branch" == "staging" ]]; then
            curl -X POST https://jenkins-staging.example.com/github-webhook/ \
              -H "Content-Type: application/json" \
              -H "X-GitHub-Event: push" \
              -d '{
                    "ref": "refs/heads/staging",
                    "repository": {
                      "full_name": "'"${GITHUB_REPO}"'",
                      "clone_url": "https://github.com/'"${GITHUB_REPO}"'.git"
                    },
                    "head_commit": {
                      "id": "'"${COMMIT_ID}"'",
                      "message": "Triggered via GitHub Actions"
                    }
                  }'

          elif [[ "$branch" == "live" ]]; then
            curl -X POST https://jenkins-prod.example.com/github-webhook/ \
              -H "Content-Type: application/json" \
              -H "X-GitHub-Event: push" \
              -d '{
                    "ref": "refs/heads/live",
                    "repository": {
                      "full_name": "'"${GITHUB_REPO}"'",
                      "clone_url": "https://github.com/'"${GITHUB_REPO}"'.git"
                    },
                    "head_commit": {
                      "id": "'"${COMMIT_ID}"'",
                      "message": "Triggered via GitHub Actions"
                    }
                  }'
          fi
